"""Added expiry on each face feature

Revision ID: 6f7707ba21f1
Revises: 01ec2d47f9cc
Create Date: 2026-08-19 20:28:35.607439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7707ba21f1'
down_revision: Union[str, Sequence[str], None] = '01ec2d47f9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_embeddings', sa.Column('expiry_date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_embeddings', 'expiry_date')
    # ### end Alembic commands ###
